---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -golang-example

resources:
  # dracon-base
  - ../base
  - gosec-producer.yaml
  - second-producer.yaml

patches:
  - path: patches/add-gosec-to-pipeline.yaml
    target:
      group: tekton.dev
      version: v1beta1
      kind: Pipeline
  - path: patches/add-second-to-pipeline.yaml
    target:
      group: tekton.dev
      version: v1beta1
      kind: Pipeline
